worms:perlinworms.cpp
	g++ -o ./worms perlinworms.cpp -O2 -lm -lpthread -I/usr/X11R6/include -L/usr/X11R6/lib -lm -lpthread -lX11 -I/usr/local/include -L/usr/local/lib -Lnoise/lib/ -lnoise

all:worms
